### PR TITLE
Added empty option to metagen

### PR DESCRIPTION
**Pull request by DoriftoShoes**
This adds an empty option to generate pack scaffolding.

### CODE REVIEW

**Comment by jfryman** [comment]
:+1: 

Any docs on how to use this? I'd like to send this to Aamir

**Comment by DoriftoShoes** [comment]
I wrote a blog back when I first wrote it but it might be out of date.  Using it looks something like this:

```
git clone https://github.com/StackStorm/st2incubator.git
cd st2incubator/etc/voodoo
```

Then to generate an empty pack:
`python etc/metagen.py --pack=FOO --author=PERSON --email=EMAIL --empty`

and the pack will be located in `output/packs`

To use the auto generation of actions it would look something like this:
`python etc/metagen.py --pack=aws --module=boto.ec2.connection --class=EC2Connection --prefix=ec2 --author=PERSON --email=EMAIL`

I'll do what I can to get more written about it later.

**Comment by DoriftoShoes** [comment]
I stand corrected on the blog.  I blogged about it when I used it for Fabric but it has changed a lot since then.

**Comment by st2stanley** [comment]
It's basic... but I added something...

https://github.com/StackStorm/st2incubator/blob/pwh/metagen/etc/voodoo/README.md <https://github.com/StackStorm/st2incubator/blob/pwh/metagen/etc/voodoo/README.md>

**Comment by jfryman** [comment]
It's basic... but I added something... 

https://github.com/StackStorm/st2incubator/blob/pwh/metagen/etc/voodoo/README.md

**Pull request merged**
